version: "3.8"
services:
  spanish-app-backend:
    container_name: spanish-app-backend
    build:
      context: packages/java
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
